--- jaaa-0.9.2/source/Makefile.orig	2021-09-27 20:01:46.032792774 +0200
+++ jaaa-0.9.2/source/Makefile	2021-09-27 20:28:35.964071029 +0200
@@ -23,9 +23,8 @@ BINDIR ?= $(PREFIX)/bin
 
 VERSION = 0.9.2
 CPPFLAGS += -MMD -MP -DVERSION=\"$(VERSION)\" -DPREFIX=\"$(PREFIX)\" -I.
-CPPFLAGS += $(shell pkgconf --cflags freetype2)
-CXXFLAGS += -O2 -Wall
-CXXFLAGS += -march=native
+CPPFLAGS += $(shell pkg-config --cflags xft)
+CXXFLAGS += -Wall
 LDLIBS += -lzita-alsa-pcmi -lclthreads -lclxclient -lasound -lpthread \
 	-lfftw3f -ljack -lXft -lX11 -lrt
 
